name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    name: Check and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
