name: Check PR
on:
  pull_request:
    branches: [main]
jobs:
  check:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
